apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: mcp-tool-sscs-context-svc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcp-tool-sscs-context-svc 
  name: mcp-tool-sscs-context-svc
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: mcp-tool-sscs-context-svc
    weight: 100 
